### Obtener usuarios
GET http://localhost:5000/api/users

### Obtener usuario por id
GET http://localhost:5000/api/user/2


### Crear usuario
POST http://localhost:5000/api/signup

Content-Type: "application/json"

{
    "name": "Cristobal",
    "email": "cristobal.colon@yahoo.es",
    "password": "admin123456"
}

### Modificar usuario
PUT http://localhost:5000/api/update/user/2
Content-Type: "application/json"

{
    "name": "Juan",
    "email": "juan23@gmail.com",
    "password": "admin123"
}

### Eliminar usuario
DELETE  http://localhost:5000/api/user/1