### Recuperar todas las tareas
GET http://localhost:5000/api/tareas


### Recuperar tarea por id
GET http://localhost:5000/api/tarea/3

### Crear tarea
POST http://localhost:5000/api/tarea
Content-Type: application/json

{
"titulo": "Crear aplicación",
"descripcion": "Aplicación de E-Commerce para UTN",
}

### Actualizar tarea
PUT http://localhost:5000/api/tarea/1

Content-Type: application/json

{
"titulo": "Crear aplicación",
"descripcion": "Aplicación de E-Commerce para UTN",
}

### Eliminar tarea
DELETE  http://localhost:5000/api/tarea/3