### Recuperar todas las tareas
GET http://localhost:5000/api/tareas


### Recuperar tarea por id
GET http://localhost:5000/api/tarea/1

### Crear tarea
POST http://localhost:5000/api/tarea
Content-Type: application/json

{
"id": 1,
"date": "08 de Septiembre, 2025",
"title": "Crear aplicación",
"description": "Aplicación de E-Commerce para UTN",
}

