### Recuperar todas las tareas
GET http://localhost:5000/api/tareas


### Recuperar tarea por id
GET http://localhost:5000/api/tarea/6

### Crear tarea
POST http://localhost:5000/api/tarea
Content-Type: application/json

{
"titulo": "Terminar la app de Matrix",
"descripcion": "Terminar con al app de los cuadrantes"
}

### Actualizar tarea
PUT http://localhost:5000/api/tarea/6

Content-Type: application/json

{
"titulo": "E-commerce para dibujos de Gerardo",
"descripcion": "Plataforma para que se logear con Google y puedan comprar dibujos o pinturas por mercado pago."
}

### Eliminar tarea
DELETE  http://localhost:5000/api/tarea/8
